name: Build e Publicacao da Imagem Docker

# Define quando o workflow sera executado
on:
  push:
    branches: [ "master" ] # Aciona o workflow em push para o branch 'master'
  pull_request:
    branches: [ "master" ] # Aciona o workflow em pull requests para o branch 'master'

# Permissoes para o GITHUB_TOKEN
permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Faz o checkout do codigo do repositorio
      - name: Checkout do Repositorio
        uses: actions/checkout@v4

      # Etapa 2: Configura o Docker Buildx (necessario para multi-plataforma e cache)
      - name: Configurar o Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Etapa 3: Faz login no Docker Hub para poder fazer o 'push' da imagem
      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Etapa 4: Extrai as tags para a imagem Docker a partir do git SHA
      - name: Extrair tags da Imagem Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/todoapp
          tags: |
            type=sha,format=long

      # Etapa 5: Constroi e publica a imagem Docker no Docker Hub
      - name: Build e Push da Imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: . # Usa o contexto do diretorio atual
          file: ./Dockerfile
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ secrets.DOCKERHUB_USERNAME }}/todoapp:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max